import { StyleSheet, Platform } from 'react-native';
import { colors } from './colors';

export const sharedStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
    paddingHorizontal: 20,
    alignItems: Platform.OS === 'web' ? 'center' : 'stretch',
  },
  contentContainer: {
    width: Platform.OS === 'web' ? 420 : '100%',
    flex: 1,
  },
  title: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: -0.3,
    marginBottom: 20,
  },
  label: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '400',
    letterSpacing: 0.3,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  input: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    color: colors.white,
    paddingHorizontal: 14,
    fontSize: 15,
    backgroundColor: colors.surfaceLight,
    marginBottom: 16,
  },
  card: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    backgroundColor: colors.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  primaryButton: {
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  primaryButtonText: {
    color: colors.black,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  outlineButton: {
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: colors.border,
    borderWidth: 1,
  },
  outlineText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: colors.surfaceLight,
    marginVertical: 8,
  },
});
